import { SimulationScenario, BenchmarkMetrics, SystemConfig } from '../types';

export const SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    id: 'full-killchain',
    name: 'Scenario 1: Complete Infiltration Kill-Chain',
    description: 'Benign baseline evolves through stealth Reconnaissance, Initial Exploitation, internal Lateral Movement, and persistent C2 beaconing.',
    expectedKillChain: ['BENIGN', 'RECONNAISSANCE', 'INITIAL_ACCESS', 'LATERAL_MOVEMENT', 'COMMAND_AND_CONTROL'],
    totalWindows: 24,
    attackStartWindow: 5,
    leadTimeExpectedSec: 140,
  },
  {
    id: 'recon-aborted',
    name: 'Scenario 2: Probed Reconnaissance (Aborted)',
    description: 'Adversary scans perimeter ports and services, but reconnaissance fails or is abandoned without gaining initial access.',
    expectedKillChain: ['BENIGN', 'RECONNAISSANCE', 'BENIGN'],
    totalWindows: 16,
    attackStartWindow: 4,
    leadTimeExpectedSec: 40,
  },
  {
    id: 'fast-lateral',
    name: 'Scenario 3: Credential Abuse & Rapid Lateral Spread',
    description: 'Stolen domain admin credentials used for immediate initial access via SMB/RDP followed by multi-host lateral pivoting.',
    expectedKillChain: ['BENIGN', 'INITIAL_ACCESS', 'LATERAL_MOVEMENT'],
    totalWindows: 18,
    attackStartWindow: 4,
    leadTimeExpectedSec: 90,
  },
  {
    id: 'stealth-c2',
    name: 'Scenario 4: Covert C2 Channel Establishment',
    description: 'Low-and-slow DNS tunneling and HTTPS jitter beaconing attempting to bypass volume-based static threshold detectors.',
    expectedKillChain: ['BENIGN', 'COMMAND_AND_CONTROL'],
    totalWindows: 18,
    attackStartWindow: 5,
    leadTimeExpectedSec: 110,
  },
  {
    id: 'data-exfiltration',
    name: 'Scenario 5: High-Entropy Data Exfiltration Burst',
    description: 'Staged sensitive intellectual property compressed and uploaded via encrypted channels to an external adversary drop server.',
    expectedKillChain: ['BENIGN', 'COMMAND_AND_CONTROL', 'EXFILTRATION'],
    totalWindows: 20,
    attackStartWindow: 6,
    leadTimeExpectedSec: 120,
  },
];

export const DEFAULT_CONFIG: SystemConfig = {
  riskThresholds: {
    normal: 0.35,
    elevated: 0.65,
    high: 0.85,
    critical: 1.0,
  },
  defaultWindowSeconds: 10,
  forecastHorizon: 5,
  deduplicationWindowSeconds: 60,
  activeModelVersion: 'CyberWorld-LSTM-v1.2 (Multi-Head Temporal Dynamics)',
};

export const BENCHMARK_DATA: BenchmarkMetrics[] = [
  {
    modelName: 'CyberWorld LSTM World Model',
    precision: 0.948,
    recall: 0.962,
    f1Score: 0.955,
    rocAuc: 0.984,
    prAuc: 0.978,
    falsePositiveRate: 0.026,
    detectionLatencyMs: 34,
    earlyWarningLeadTimeSec: 142,
    forecastAccuracyT1: 0.938,
    forecastAccuracyT3: 0.892,
    forecastAccuracyT5: 0.841,
    isWorldModel: true,
  },
  {
    modelName: 'Random Forest (Static Isolated Flows)',
    precision: 0.881,
    recall: 0.846,
    f1Score: 0.863,
    rocAuc: 0.912,
    prAuc: 0.895,
    falsePositiveRate: 0.074,
    detectionLatencyMs: 12,
    earlyWarningLeadTimeSec: 0,
    forecastAccuracyT1: 0.0,
    forecastAccuracyT3: 0.0,
    forecastAccuracyT5: 0.0,
    isWorldModel: false,
  },
  {
    modelName: 'Logistic Regression (Baseline Linear)',
    precision: 0.792,
    recall: 0.764,
    f1Score: 0.778,
    rocAuc: 0.824,
    prAuc: 0.801,
    falsePositiveRate: 0.128,
    detectionLatencyMs: 4,
    earlyWarningLeadTimeSec: 0,
    forecastAccuracyT1: 0.0,
    forecastAccuracyT3: 0.0,
    forecastAccuracyT5: 0.0,
    isWorldModel: false,
  },
];

export const ATTACK_STAGE_INFO: Record<string, { label: string; color: string; bg: string; border: string; description: string }> = {
  BENIGN: {
    label: 'Benign Traffic',
    color: '#10b981',
    bg: 'rgba(16, 185, 129, 0.1)',
    border: 'rgba(16, 185, 129, 0.3)',
    description: 'Standard enterprise business telemetry, authorized services, and healthy protocols.',
  },
  RECONNAISSANCE: {
    label: 'Reconnaissance',
    color: '#38bdf8',
    bg: 'rgba(56, 189, 248, 0.1)',
    border: 'rgba(56, 189, 248, 0.3)',
    description: 'Active port probing, service enumeration, OS fingerprinting, and subnet discovery sweeps.',
  },
  INITIAL_ACCESS: {
    label: 'Initial Access',
    color: '#fbbf24',
    bg: 'rgba(251, 191, 36, 0.1)',
    border: 'rgba(251, 191, 36, 0.3)',
    description: 'Public-facing exploit delivery, credential stuffing, password spraying, or phish payload execution.',
  },
  LATERAL_MOVEMENT: {
    label: 'Lateral Movement',
    color: '#f97316',
    bg: 'rgba(249, 115, 22, 0.1)',
    border: 'rgba(249, 115, 22, 0.3)',
    description: 'SMB/RDP internal pivots, Pass-the-Hash, remote WMI execution, and internal token reuse.',
  },
  COMMAND_AND_CONTROL: {
    label: 'Command & Control',
    color: '#ef4444',
    bg: 'rgba(239, 68, 68, 0.1)',
    border: 'rgba(239, 68, 68, 0.3)',
    description: 'Periodic heartbeats, DNS tunneling beacons, encrypted outbound channels to adversary infrastructure.',
  },
  EXFILTRATION: {
    label: 'Exfiltration',
    color: '#dc2626',
    bg: 'rgba(220, 38, 38, 0.15)',
    border: 'rgba(220, 38, 38, 0.4)',
    description: 'High-volume compressed data transfer, unauthorized cloud uploads, or staged exfil over external channels.',
  },
};
